# Generated by Django 5.1.1 on 2024-09-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_charity_address_remove_charity_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='created_at',
        ),
    ]
