# Generated by Django 5.1.1 on 2024-09-18 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_charity_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='phone_number',
            new_name='recipient_phone',
        ),
        migrations.AddField(
            model_name='transaction',
            name='charity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.charity'),
        ),
    ]
