# Generated by Django 5.1.1 on 2024-09-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_phone_number_transaction_recipient_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='recipient_phone',
            new_name='phone_number',
        ),
    ]
