# Generated by Django 5.1.1 on 2024-09-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_recipient_phone_transaction_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Transfer', 'Transfer'), ('Recharge Phone', 'Recharge Phone'), ('Charity', 'Charity Transfer')], max_length=50),
        ),
    ]
