# Generated by Django 5.1.1 on 2024-09-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_transaction_transaction_type'),
    ]

    operations = [
    ]
